
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahjzgzfhyckqxtlhtsqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoanpnemZoeWNrcXh0bGh0c3FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNjY5MzIsImV4cCI6MjA1Mjk0MjkzMn0.iFhfCQC2qcYF06hzHRNXTmrQI2-CY4hSxV8BgjwJxlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Re-export utility functions for backward compatibility
export {
  calculateFee,
  formatCurrency,
  getCurrencyForCountry,
  convertCurrency
} from "@/lib/utils/currency";
